### ISSUE TITLE
Create .gitignore to not commit unneeded files to git

### ISSUE THREAD

**Issue by fernandojunior** [bluegardier/airbnb_prediction#2]
Avoid commit trash files/folders like `.ipynb_checkpoints` and `__pycache__`.

Create a `bluegardier/airbnb_prediction/.gitignore` file containing a extension list of files to not commit.

Example:
- https://github.com/github/gitignore/blob/master/Python.gitignore

PS: Please, don't forget to remove already commited trash files (`.ipynb_checkpoints`, `__pycache__`, etc.)

**Comment by bluegardier** [comment]
Done!
