### ISSUE TITLE
Store statical/initial variables into config.py module

### ISSUE THREAD

**Issue by fernandojunior** [bluegardier/airbnb_prediction#4]
Centralize all static variable/object/constant variables (not sensitive) into a config module or file. In this way, you can find/manage/share common objects more easily.

For example, move all `objects.py` variables to `config.py` module

If your config module/file increase or have sensitive variables in future, you can create config submodules/subfiles or read from OS environment.

Some refs:
- https://12factor.net/config
- https://github.com/theskumar/python-dotenv

**Comment by bluegardier** [comment]
Done!
