### ISSUE TITLE
Configure your Setuptools

### ISSUE THREAD

**Issue by fernandojunior** [bluegardier/airbnb_prediction#5]
> [Setuptools](https://setuptools.readthedocs.io/en/latest/userguide/index.html) is a collection of enhancements to the Python distutils that allow developers to more easily build and distribute Python packages, especially ones that have dependencies on other packages.

By configuring correctly your project using setuptools, you can install it in any other python project using `pip install` for example.

TODO:
- `setup.py` should be in root folder of your repository. Move `bluegardier/airbnb_prediction/airbnb_prediction/setup.py` to `bluegardier/airbnb_prediction/setup.py`
- Fill other relevant fields into setup.py. See example https://github.com/NeowayLabs/data-science-template/blob/master/template/setup.py
- Move all files from `bluegardier/airbnb_prediction/airbnb_prediction/airbnb_prediction/*` to parent folder `bluegardier/airbnb_prediction/airbnb_prediction`.
- And remove uneeded folder `bluegardier/airbnb_prediction/airbnb_prediction/airbnb_prediction/*`

**Comment by bluegardier** [comment]
Done!
