### ISSUE TITLE
Split the README.md into sections

### ISSUE THREAD

**Issue by fernandojunior** [bluegardier/airbnb_prediction#6]
First, rename ~~readme.md~~ to README.md

Then, update the README.md as the following sections:

1. Project description: Simple explanation of the main objective and target population
2. Data Dependencies: Simple data dictionary to describe the data sources and input columns
2. Usage: How we can reproduce your experiment?
3. Repository structure: Simple explanation on folders and files structures

Some refs:
- https://docs.github.com/pt/github/creating-cloning-and-archiving-repositories/about-readmes
- https://blog.rocketseat.com.br/como-fazer-um-bom-readme/

For example:

# <Title>

## Project Description

This project is a `<type_of_modeling>` that `<do_something>` to solve `<this_problem>` aimed to the clients of the `<some_business>`.

## Data Dependencies

We are using the following Data Sources:

| Source  | Description  | Year              |
| ---------  | ----------------  | ------             |
| Some Company    | ...                  |  2000 - 2021

Input Columns:
| Column | Source | Type    | Description   |
| ---------  | ---------- | --------- | ----------------  |        
| *X1* | ... | int | ...  |
| *X2* | ... | int | ...  |
| *X3* | ... | bool | ... |
| *Y1* | ... | str | ... |

## Usage

To run this project locally:

```sh
git clone <LINK TO THE REPO>
cd <REPO>
pip install -r requirements.txt
jupyter notebook <MAIN EXPERIMENT NAME>
```

To run this project on Google Colab:
- < PUT Google Colab link here >

## Repository structure

- `docs`: contains extra documentation of the project
- `notebooks`: contains jupyter notebook experiments needed to collect, explore, prepare data, train and evaluate data.
- `requirements.txt`: contains python dependencies to reproduce the experiments.

**Comment by bluegardier** [comment]
Done!

**Comment by fernandojunior** [comment]
Nice!

Later, try to improve README to describe input columns from raw dataset to give us better understand of data dependencies

**Comment by bluegardier** [comment]
I'll do it soon, as there are over 70 columns and some of them I actually don't know it's meaning.

**Comment by fernandojunior** [comment]
> I'll do it soon, as there are over 70 columns and some of them I actually don't know it's meaning.

Don't worry! It is just nit picking haha 
You can ignore if you think it isn't necessary

Ref:
- https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.

**Comment by bluegardier** [comment]
> > I'll do it soon, as there are over 70 columns and some of them I actually don't know it's meaning.
> 
> Don't worry! It is just nit picking haha
> You can ignore if you think it isn't necessary
> 
> Ref:
> 
> * https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.

Thanks for all these refs!!
