### ISSUE TITLE
Use a linter tool to adjust code style based on PEP8

### ISSUE THREAD

**Issue by fernandojunior** [bluegardier/airbnb_prediction#7]
Suggested libs:
- [flake8](https://gitlab.com/pycqa/flake8) (find lint warnings)
- [pylint](https://github.com/PyCQA/pylint) (find lint warnings)
- [black](https://github.com/psf/black) (automatic formater)
- [flake8-black](https://github.com/peterjc/flake8-black) (automatic formater based on flake8 warnings)

Refs:
- https://www.python.org/dev/peps/pep-0008/#imports

**Comment by bluegardier** [comment]
my pycharm already comes with a linter tool. Whenever I click "reformat file", the editor makes the proper changes to match the code style.

**Comment by fernandojunior** [comment]
I see. By now, I think you can close this issue. Reopen it when you want to learn a little bit about CI/CD on Github

**Comment by bluegardier** [comment]
> I see. By now, I think you can close this issue. Reopen it when you want to learn a little bit about CI/CD on Github

I'll let it open because I do want to learn about it now haha.

**Comment by fernandojunior** [comment]
Great!

Let's start simple!

You can configure Github Actions as a Continuous Integration (CI) tool to automatically use these libs to fix and find lint warnnigs/erros.

Later, we can improve it to work also as a Continuous Delivery tool.

Refs:
- https://www.youtube.com/watch?v=IPLTUlRFxgo
- https://docs.github.com/pt/actions/guides/building-and-testing-python
- https://github.com/fernandojunior/financial-fraud-detection/blob/master/.github/workflows/pythonpackage.yml

**Comment by bluegardier** [comment]
Done!

You can see the workflow folder in the ```main``` branch. 

I saw the video and your code. The `` yml`` is extremely intuitive, so just looking at it, I already understood 90% of what’s happening there. However, I didn’t want to do the same exactly as you did, so I looked for a different solution to do it myself. It is extremely basic, but it worked. I ran and saw it point out the errors, so I made adjustments and saw them disappear from the report. But the code itself is very extensive and I'm not in the mood to spend an hour making line adjustments hahaha. So, in the following projects, I will create this file from scratch to avoid this behavior!
