### ISSUE TITLE
Create main.py module to put all things together and use as a CLI

### ISSUE THREAD

**Issue by fernandojunior** [bluegardier/airbnb_prediction#8]
Create a `airbnb_prediction/main.py` module to run each step of your pipeline experiment (generate features, train model, evaluate, etc.). This module will be used as an low level interface (ie CLI) for a given user to deploy your model.

TODO:

- [x] Create file `airbnb_prediction/main.py` with suggested structure:

```python
import fire

def features():
     ''' Put necessary code to split data, clean, generate, preprocess and save features (listings_train.csv and listings_test.csv)'''
     pass


def deploy_model():
    ''' Put necessary code to load features, train model, finalize model and save model '''

    # Preprocess Step
    df = load(...listings_train.csv)

    # Model Stage
    print('Starting Model Stage')
    model = modelling.RegressorTrainer(df.drop('id', axis=1), 'price', "testing")

    print('Setting up Pycaret Environment')
    model.start_session()

    print("Training The Model")
    model.train_model()

    print("Finalizing The Model")
    model.finalize_model()

    print('Generated Model Saved at: {}'.format(config.model_path))
    model.save_model("{}/model".format(config.model_path))


def evaluate_model():
    ''' Put necessary code to load the model, load test data (unseen), evaluate model and save metrics '''
    df = pd.read_csv(...listings_test.csv...)
    ...


def run():
    features()
    deploy_model()
    evaluate_model()


def cli():
    """ Caller to transform module in a low-level CLI """
    return 

if __name__ == '__main__':
    cli()
```

- [x] Update Usage section from README.py to tech us how to run each step

> python main.py --help  # Shows usage information.
> python main.py features # Generate features
> python main.py deploy_model # Deploy model
> python main.py evaluate_model # Evaluate model
> python main.py run # Run all model pipeline steps sequencially 

- [x] Remove uneeded `airbnb_prediction/train.py` module

Ref:
- https://github.com/google/python-fire
- https://github.com/NeowayLabs/data-science-template/blob/master/template/model_name/main.py

**Comment by bluegardier** [comment]
I'm kinda confused here.  Should I use the same code from `train.py` in `features` and `deploy_model`?

**Comment by bluegardier** [comment]
Forget it! Just read the last section you posted

**Comment by bluegardier** [comment]
Right. The first step is done. However, it's not totally clear how this `fire` works for me kkk. By looking at the references you sent me, I could see the function's argument was using **kwargs, while mine's not. Was this supposed to be declared when the user is using the CLI?

**Comment by fernandojunior** [comment]
> Right. The first step is done. However, it's not totally clear how this `fire` works for me kkk. By looking at the references you sent me, I could see the function's argument was using **kwargs, while mine's not. Was this supposed to be declared when the user is using the CLI?

`**kwargs`  are used to input some parameters when the user runs some command.

Let's suppose the user can pass optional file names to dump train and test sets in features function. The features function will need to be refactored to somthing like:

```python
def features(**kwargs):
    """
    Method to split, clean and preprocess data.
    :return:
    """
    # Get `data_train_path` arg from user input, or use default path if arg is `None`
    train_path = kwargs.get('data_train_path', '../data/processed/data_train.pickle')
    test_path = kwargs.get('data_test_path', '../data/processed/data_test.pickle')

    # Splits
    df_train, df_test = preprocess.spliting_dataset()

    preprocess.preprocess_data(df_train)
    preprocess.preprocess_data(df_test)

    pickle.dump(df_train, open(train_path, 'wb'))
    pickle.dump(df_test, open(test_path, 'wb'))
```

Alternatively, you can refact to make the arguments more explicit:

```python
def features(data_train_path: str = config.data_train_path, data_train_path: str = config.data_test_path):
    """
    Method to split, clean and preprocess data.
    :return:
    """
    ...
```

This way, a user can run the feature step passing some argument via command line:

```sh
python main.py features --data_train_path=some/path/to/save/train/data.csv
```

**Comment by bluegardier** [comment]
> > Right. The first step is done. However, it's not totally clear how this `fire` works for me kkk. By looking at the references you sent me, I could see the function's argument was using **kwargs, while mine's not. Was this supposed to be declared when the user is using the CLI?
> 
> `**kwargs` are used to input some parameters when the user runs some command.
> 
> Let's suppose the user can pass optional file names to dump train and test sets in features function. The features function will need to be refactored to somthing like:
> 
> ```python
> def features(**kwargs):
>     """
>     Method to split, clean and preprocess data.
>     :return:
>     """
>     # Get `data_train_path` arg from user input, or use default path if arg is `None`
>     train_path = kwargs.get('data_train_path', '../data/processed/data_train.pickle')
>     test_path = kwargs.get('data_test_path', '../data/processed/data_test.pickle')
> 
>     # Splits
>     df_train, df_test = preprocess.spliting_dataset()
> 
>     preprocess.preprocess_data(df_train)
>     preprocess.preprocess_data(df_test)
> 
>     pickle.dump(df_train, open(train_path, 'wb'))
>     pickle.dump(df_test, open(test_path, 'wb'))
> ```
> 
> Alternatively, you can refact to make the arguments more explicit:
> 
> ```python
> def features(data_train_path: str = config.data_train_path, data_train_path: str = config.data_test_path):
>     """
>     Method to split, clean and preprocess data.
>     :return:
>     """
>     ...
> ```
> 
> This way, a user can run the feature step passing some argument via command line:
> 
> ```shell
> python main.py features --data_train_path=some/path/to/save/train/data.csv
> ```

about that, I tried to refactor the code as you exemplified above as:

```
def features(**kwargs):
    """
    Method to split, clean and preprocess data.
    :return:
    """

    train_save_path = kwargs.get(path, '../data/processed/data_train.pickle')

    # Splits
    df_train, df_test = preprocess.spliting_dataset()

    preprocess.preprocess_data(df_train)
    preprocess.preprocess_data(df_test)

    pickle.dump(df_train, open(train_save_path, 'wb'))
    pickle.dump(df_test, open('../data/processed/data_test.pickle', 'wb'))
    print("Generating Datasets for Model Training")

```

However, The pickle were always saved at the default ```kwargs.get()``` argument:  '../data/processed/data_train.pickle'
whenever I typed:

 ```python3 main.py features --train_save_path='../data/model/data_train.pickle'``` or ```python3 main.py features --train_save_path=../data/model/data_train.pickle```

When I tried the following, it worked:

```
def features(path: str):
    """
    Method to split, clean and preprocess data.
    :return:
    """

    #train_save_path = kwargs.get(path, '../data/processed/data_train.pickle')

    # Splits
    df_train, df_test = preprocess.spliting_dataset()

    preprocess.preprocess_data(df_train)
    preprocess.preprocess_data(df_test)

    pickle.dump(df_train, open(path, 'wb'))
    pickle.dump(df_test, open('../data/processed/data_test.pickle', 'wb'))
    print("Generating Datasets for Model Training")
```

CLI: python3 main.py features --train_save_path='../data/model/data_train.pickle'

**Comment by bluegardier** [comment]
All done!

**Comment by fernandojunior** [comment]
Nice!
